"use client";

import { useState } from "react";
import { ChevronDown, HelpCircle, PhoneCall } from "lucide-react";

export function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs = [
    {
      question: "How quickly can ClickLab launch our Google Ads & SEO campaign?",
      answer:
        "We can launch fully-configured, high-intent Google search campaigns within 5 to 7 business days after initial onboarding, including negative-keyword lists, custom landing pages, and direct call routing.",
    },
    {
      question: "Do you handle LegitScript certification and Google compliance?",
      answer:
        "Yes. We specialize exclusively in US healthcare & addiction treatment compliance. Our team guides your facility through the LegitScript certification requirements and ensures all Google Ads policies are 100% satisfied.",
    },
    {
      question: "Are the phone call leads exclusive to our treatment center?",
      answer:
        "100% exclusive. Every phone call and web inquiry generated by your ClickLab campaign goes directly and exclusively to your admissions desk. We never share or resell leads to third parties.",
    },
    {
      question: "What commercial insurance qualification rates can we expect?",
      answer:
        "Our campaigns target high-intent private pay and commercial insurance keywords (PPO/HMO). Our client partners typically report a 40% to 65%+ commercial insurance qualification rate on inbound calls.",
    },
    {
      question: "What is required to start a campaign for our facility?",
      answer:
        "To get started, we conduct a 20-minute strategy call to analyze your bed capacity, target geographic markets, and current intake workflow. You can call us directly at (216) 408-8962.",
    },
  ];

  return (
    <section className="py-16 sm:py-24 bg-white relative overflow-hidden">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="text-center mb-12 sm:mb-16">
          <div className="inline-flex items-center gap-2 bg-blue-50 border border-blue-200 rounded-full px-4 py-1.5 text-xs font-black text-blue-700 uppercase tracking-widest mb-4">
            <HelpCircle className="w-3.5 h-3.5" /> Frequently Asked Questions
          </div>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black text-slate-900 tracking-tight leading-tight mb-4">
            Got Questions? We Have Answers.
          </h2>
          <p className="text-sm sm:text-base text-slate-600 font-normal">
            Everything you need to know about scaling admissions with ClickLab.
          </p>
        </div>

        {/* FAQ Items */}
        <div className="space-y-4">
          {faqs.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div
                key={faq.question}
                className="bg-slate-50 border border-slate-200 rounded-2xl overflow-hidden transition-all"
              >
                <button
                  onClick={() => setOpenIndex(isOpen ? null : idx)}
                  className="w-full p-5 sm:p-6 text-left flex items-center justify-between gap-4 font-black text-base sm:text-lg text-slate-900 hover:text-blue-600 transition-colors"
                >
                  <span>{faq.question}</span>
                  <div
                    className={`w-8 h-8 rounded-xl bg-white border border-slate-200 flex items-center justify-center shrink-0 transition-transform duration-300 ${
                      isOpen ? "rotate-180 bg-blue-50 border-blue-300 text-blue-600" : "text-slate-500"
                    }`}
                  >
                    <ChevronDown className="w-4 h-4" />
                  </div>
                </button>

                {isOpen && (
                  <div className="px-5 sm:px-6 pb-6 pt-0 text-xs sm:text-sm text-slate-600 font-medium leading-relaxed border-t border-slate-200/60 mt-1 pt-4">
                    {faq.answer}
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Direct Phone Assistance Banner */}
        <div className="mt-12 text-center bg-blue-50 border border-blue-200/80 rounded-2xl p-6 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="text-center sm:text-left">
            <h4 className="text-base font-black text-slate-900">Have a specific question about your facility?</h4>
            <p className="text-xs text-slate-600 font-medium">Speak directly with a senior healthcare growth strategist today.</p>
          </div>
          <a
            href="tel:2164088962"
            className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-black text-xs uppercase tracking-wider px-5 py-3 rounded-xl shadow-md transition-all shrink-0"
          >
            <PhoneCall className="w-4 h-4" />
            <span>Call (216) 408-8962</span>
          </a>
        </div>
      </div>
    </section>
  );
}
